import { MetadataRoute } from 'next';

/**
 * Generates the `robots.txt` file for search engine crawlers.
 *
 * This file is automatically served at `/robots.txt` by Next.js when using the
 * Metadata Route API. It tells crawlers which parts of the site they are allowed
 * to index and where to find the sitemap.
 *
 * @see https://nextjs.org/docs/app/api-reference/file-conventions/metadata/robots
 */
export default function robots(): MetadataRoute.Robots {
  const baseUrl = 'https://vivanapolinotodden.no';

  return {
    rules: {
      userAgent: '*', // Applies to all crawlers
      allow: '/', // Allow crawling of the homepage
      /**
       * Disallow crawling of admin pages and the order success page.
       *
       * - `/admin` and `/admin/` contain sensitive backend functionality.
       * - `/order/success` is a thank‑you page that doesn't need to be indexed
       *   (it may contain order‑specific parameters that could lead to duplicate
       *   content).
       */
      disallow: ['/admin', '/admin/', '/order/success'],
    },
    /**
     * Link to the XML sitemap.
     *
     * The sitemap is generated by `sitemap.ts` and served at `/sitemap.xml`.
     * Providing it here helps search engines discover all indexed pages faster.
     */
    sitemap: `${baseUrl}/sitemap.xml`,
  };
}
