package handler

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"github.com/kirinyoku/vivanapoli/backend/internal/config"
	"github.com/kirinyoku/vivanapoli/backend/internal/db/generated"
	"github.com/resend/resend-go/v3"
	"github.com/rs/cors"
)

// Handler serves as the central dependency container for all API logic.
// It holds database queries, app configuration, and external service clients.
type Handler struct {
	queries *generated.Queries // Type-safe SQL queries generated by sqlc
	config  *config.Config     // Environment-based configuration
	resend  *resend.Client     // Email service client (Resend)
}

// New initializes the Handler with its required dependencies.
func New(queries *generated.Queries, config *config.Config) *Handler {
	client := resend.NewClient(config.ResendApiKey)

	return &Handler{
		queries: queries,
		config:  config,
		resend:  client,
	}
}

// SetupRoutes configures the routing tree using Chi.
// It handles middleware application and groups endpoints by access level.
func (h *Handler) SetupRoutes() *chi.Mux {
	r := chi.NewRouter()

	// Standard middleware stack for logging, panic recovery, and CORS.
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)
	r.Use(h.corsMiddleware())

	// Simple health check for deployment readiness probes.
	r.Get("/health", h.handleHealth)

	// API endpoints group
	r.Route("/api", func(r chi.Router) {
		// --- Public Endpoints ---
		r.Get("/menu", h.GetMenu)          // Returns the full menu grouped by category
		r.Get("/settings", h.GetSettings)  // Returns restaurant info (hours, phone, etc.)
		r.Post("/orders", h.CreateOrder)   // Places a new order and triggers email

		// --- Admin Authentication ---
		r.Post("/admin/login", h.Login)

		// --- Protected Admin Routes ---
		r.Group(func(r chi.Router) {
			r.Use(h.AdminOnly)

			// Category management
			r.Route("/admin/menu/categories", func(r chi.Router) {
				r.Get("/", h.AdminGetCategories)
				r.Post("/", h.AdminCreateCategory)
				r.Put("/{id}", h.AdminUpdateCategory)
				r.Delete("/{id}", h.AdminDeleteCategory)
			})

			// Item management (Prices, Availability, Allergens)
			r.Route("/admin/menu/items", func(r chi.Router) {
				r.Get("/", h.AdminGetMenuItems)
				r.Post("/", h.AdminCreateMenuItem)
				r.Put("/{id}", h.AdminUpdateMenuItem)
				r.Delete("/{id}", h.AdminDeleteMenuItem)
			})

			// Order management (Viewing and Status updates)
			r.Route("/admin/orders", func(r chi.Router) {
				r.Get("/", h.AdminGetOrders)
				r.Put("/{id}/status", h.AdminUpdateOrderStatus)
			})

			// Global settings management
			r.Route("/admin/settings", func(r chi.Router) {
				r.Put("/", h.AdminUpdateSettings)
			})
		})
	})

	return r
}

// corsMiddleware configures Cross-Origin Resource Sharing based on app config.
func (h *Handler) corsMiddleware() func(http.Handler) http.Handler {
	c := cors.New(cors.Options{
		AllowedOrigins: h.config.AllowedOrigins,
		AllowedMethods: []string{
			http.MethodGet,
			http.MethodPost,
			http.MethodPut,
			http.MethodDelete,
			http.MethodOptions,
		},
		AllowedHeaders: []string{
			"Accept",
			"Authorization",
			"Content-Type",
		},
		AllowCredentials: true,
		MaxAge:           300, // Cache preflight response for 5 minutes
	})

	return c.Handler
}

func (h *Handler) handleHealth(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(`{"status": "ok"}`))
}
