// Package handler implements the HTTP transport layer.
// It follows the "handler struct" pattern popularised by Go's net/http:
// the Handler struct acts as a dependency container, and its methods
// are the HTTP handlers. This avoids global state and makes testing
// straightforward (inject a mock *generated.Queries via New).
package handler

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"github.com/kirinyoku/vivanapoli/backend/internal/config"
	"github.com/kirinyoku/vivanapoli/backend/internal/db/generated"
	"github.com/resend/resend-go/v3"
	"github.com/rs/cors"
)

// Handler serves as the central dependency container for all API logic.
// It holds database queries, app configuration, and external service clients.
// All fields are unexported to enforce dependency injection through New().
type Handler struct {
	queries *generated.Queries // Type-safe SQL queries generated by sqlc
	config  *config.Config     // Environment-based configuration
	resend  *resend.Client     // Email service client (Resend)
}

// New initializes the Handler with its required dependencies.
// The Resend client is created internally rather than injected because it
// has no mock interface — tests that must not send real emails can simply
// leave the API key empty (sendOrderEmail skips sending in that case).
func New(queries *generated.Queries, config *config.Config) *Handler {
	client := resend.NewClient(config.ResendApiKey)

	return &Handler{
		queries: queries,
		config:  config,
		resend:  client,
	}
}

// SetupRoutes configures the routing tree using Chi.
// It handles middleware application and groups endpoints by access level.
//
// Route organisation:
//   - Public routes (/api/menu, /api/settings, /api/orders) require no auth.
//   - /api/admin/login is deliberately placed outside the AdminOnly group
//     because it must be accessible without a token.
//   - All /api/admin/* routes are wrapped in h.AdminOnly JWT middleware.
func (h *Handler) SetupRoutes() *chi.Mux {
	r := chi.NewRouter()

	// Standard middleware stack for logging, panic recovery, and CORS.
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)
	r.Use(h.corsMiddleware())

	// Health check — no prefix, always accessible for k8s/lb readiness probes.
	r.Get("/health", h.handleHealth)

	// API endpoints group
	r.Route("/api", func(r chi.Router) {
		// --- Public Endpoints ---
		r.Get("/menu", h.GetMenu)          // Full menu grouped by category
		r.Get("/settings", h.GetSettings)  // Restaurant info (hours, phone, etc.)
		r.Post("/orders", h.CreateOrder)   // New order + email notification

		// --- Admin Authentication (no token required) ---
		r.Post("/admin/login", h.Login)

		// --- Protected Admin Routes ---
		r.Group(func(r chi.Router) {
			r.Use(h.AdminOnly)

			// Category management
			r.Route("/admin/menu/categories", func(r chi.Router) {
				r.Get("/", h.AdminGetCategories)
				r.Post("/", h.AdminCreateCategory)
				r.Put("/{id}", h.AdminUpdateCategory)
				r.Delete("/{id}", h.AdminDeleteCategory)
			})

			// Item management (Prices, Availability, Allergens)
			r.Route("/admin/menu/items", func(r chi.Router) {
				r.Get("/", h.AdminGetMenuItems)
				r.Post("/", h.AdminCreateMenuItem)
				r.Put("/{id}", h.AdminUpdateMenuItem)
				r.Delete("/{id}", h.AdminDeleteMenuItem)
			})

			// Order management (Viewing and Status updates)
			r.Route("/admin/orders", func(r chi.Router) {
				r.Get("/", h.AdminGetOrders)
				r.Put("/{id}/status", h.AdminUpdateOrderStatus)
			})

			r.Get("/admin/stats", h.AdminGetStats)

			// Global settings management
			r.Route("/admin/settings", func(r chi.Router) {
				r.Put("/", h.AdminUpdateSettings)
			})
		})
	})

	return r
}

// corsMiddleware configures Cross-Origin Resource Sharing based on app config.
// MaxAge is set to 300 seconds (5 minutes) so browsers cache the preflight
// response, reducing OPTIONS requests during normal usage.
func (h *Handler) corsMiddleware() func(http.Handler) http.Handler {
	c := cors.New(cors.Options{
		AllowedOrigins: h.config.AllowedOrigins,
		AllowedMethods: []string{
			http.MethodGet,
			http.MethodPost,
			http.MethodPut,
			http.MethodDelete,
			http.MethodOptions,
		},
		AllowedHeaders: []string{
			"Accept",
			"Authorization",
			"Content-Type",
		},
		AllowCredentials: true,
		MaxAge:           300,
	})

	return c.Handler
}

// handleHealth responds with a simple JSON status.
// Used by Kubernetes/Docker health checks — keep it lightweight and
// avoid querying the database here to prevent cascading failures.
func (h *Handler) handleHealth(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(`{"status": "ok"}`))
}
